/**
 * Turns the generated asset sheets in assets/raw/ into transparent sprites and
 * inlines them as data URIs.
 *
 * The sheets are generated on a pure green field, which this script keys out;
 * the pilgrim sheet is then split into individual figures by scanning for
 * columns that are fully transparent. Everything ends up in src/sprite-data.ts
 * because the bundler does not serve public/ in this environment.
 *
 *   node scripts/prepare-sprites.mjs
 */
import { Jimp } from "jimp";
import { writeFileSync } from "node:fs";

const GREEN = { r: 0, g: 255, b: 0 };
/** How far a pixel may sit from pure green and still count as background. */
const KEY_TOLERANCE = 108;
/** Alpha below this is treated as empty when looking for gaps between figures. */
const EMPTY_ALPHA = 12;

const distanceToGreen = (r, g, b) =>
  Math.sqrt((r - GREEN.r) ** 2 + (g - GREEN.g) ** 2 + (b - GREEN.b) ** 2);

/** Replaces the green field with transparency and de-fringes the edges. */
const keyOut = (image) => {
  image.scan(0, 0, image.bitmap.width, image.bitmap.height, (x, y, idx) => {
    const { data } = image.bitmap;
    const [r, g, b] = [data[idx], data[idx + 1], data[idx + 2]];
    const distance = distanceToGreen(r, g, b);

    if (distance < KEY_TOLERANCE) {
      data[idx + 3] = 0;
      return;
    }

    // Pull the green cast out of the semi-transparent rim left by the key.
    if (g > r && g > b && distance < KEY_TOLERANCE * 1.8) {
      const cap = Math.max(r, b);
      data[idx + 1] = Math.round(g * 0.35 + cap * 0.65);
      data[idx + 3] = Math.round(255 * ((distance - KEY_TOLERANCE) / (KEY_TOLERANCE * 0.8)));
    }
  });
  return image;
};

const columnIsEmpty = (image, x) => {
  const { data, height } = { data: image.bitmap.data, height: image.bitmap.height };
  for (let y = 0; y < height; y++) {
    if (data[(y * image.bitmap.width + x) * 4 + 3] > EMPTY_ALPHA) return false;
  }
  return true;
};

/** Finds runs of non-empty columns — one run per figure on the sheet. */
const findSpans = (image, minWidth = 40) => {
  const spans = [];
  let start = null;

  for (let x = 0; x < image.bitmap.width; x++) {
    const empty = columnIsEmpty(image, x);
    if (!empty && start === null) start = x;
    if (empty && start !== null) {
      if (x - start >= minWidth) spans.push([start, x]);
      start = null;
    }
  }
  if (start !== null && image.bitmap.width - start >= minWidth) {
    spans.push([start, image.bitmap.width]);
  }
  return spans;
};

/** Crops away fully transparent rows above and below. */
const trimVertically = (image) => {
  const { width, height, data } = image.bitmap;
  let top = 0;
  let bottom = height - 1;

  const rowIsEmpty = (y) => {
    for (let x = 0; x < width; x++) {
      if (data[(y * width + x) * 4 + 3] > EMPTY_ALPHA) return false;
    }
    return true;
  };

  while (top < height && rowIsEmpty(top)) top++;
  while (bottom > top && rowIsEmpty(bottom)) bottom--;
  return image.crop({ x: 0, y: top, w: width, h: bottom - top + 1 });
};

const toDataUri = async (image, targetHeight) => {
  if (targetHeight && image.bitmap.height > targetHeight) {
    image.resize({ h: targetHeight });
  }
  const buffer = await image.getBuffer("image/png");
  return `data:image/png;base64,${buffer.toString("base64")}`;
};

const main = async () => {
  const lines = [
    "// Generated by scripts/prepare-sprites.mjs — do not edit by hand.",
    "// Sprites are inlined because the bundler does not serve public/ here.",
    "",
  ];

  // --- pilgrims -----------------------------------------------------------
  const sheet = keyOut(await Jimp.read("assets/raw/pilgrims.png"));
  const spans = findSpans(sheet);
  console.log(`pilgrim sheet: ${spans.length} figures found`);

  const sprites = [];
  for (const [from, to] of spans) {
    const figure = trimVertically(
      sheet.clone().crop({ x: from, y: 0, w: to - from, h: sheet.bitmap.height }),
    );
    sprites.push(await toDataUri(figure, 420));
  }

  lines.push(`export const PILGRIM_SPRITES = [\n${sprites
    .map((s) => `  "${s}",`)
    .join("\n")}\n];`);
  lines.push("");

  // --- kaaba --------------------------------------------------------------
  const kaaba = trimVertically(keyOut(await Jimp.read("assets/raw/kaaba.png")));
  lines.push(`export const KAABA_SPRITE =\n  "${await toDataUri(kaaba, 900)}";`);
  lines.push("");

  writeFileSync("src/sprite-data.ts", lines.join("\n"));

  const kb = (lines.join("\n").length / 1024).toFixed(0);
  console.log(`wrote src/sprite-data.ts (${kb}KB, ${sprites.length} pilgrims + kaaba)`);
};

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
